---
- name: Define temp dir for downloading artifacts
  ansible.builtin.set_fact:
    artifact_download_dir: "{{ staging_dir }}/temp"

- name: Create artifacts folder
  ansible.builtin.file:
    state: directory
    path: "{{ artifact_download_dir }}"

#### Get OC CLI
- name: Download OC CLI archive
  ansible.builtin.get_url:
    url: "{{ ocp_bin_client_url }}"
    dest: "{{ artifact_download_dir }}"

- name: Extract OC CLI archive
  ansible.builtin.unarchive:
    src: "{{ artifact_download_dir }}/{{ ocp_bin_client_archive_name }}"
    dest: "{{ artifact_download_dir }}"

- name: Copy OC CLI to staging directory
  ansible.builtin.copy:
    src: "{{ artifact_download_dir }}/oc"
    dest: "{{ oc_bin }}"
    mode: '0755'

#### Get OCP Installer
- name: Download OCP Installer archive
  ansible.builtin.get_url:
    url: "{{ ocp_bin_installer_url }}"
    dest: "{{ artifact_download_dir }}"
  when: destroy is not defined or destroy == false

- name: Extract OCP Installer archive
  ansible.builtin.unarchive:
    src: "{{ artifact_download_dir }}/{{ ocp_bin_installer_archive_name }}"
    dest: "{{ staging_dir }}"
  when: destroy is not defined or destroy == false

#### Get RHCOS Image
- name: Download RHCOS archive
  ansible.builtin.get_url:
    url: "{{ rhcos_bin_qcow_url }}"
    dest: "{{ artifact_download_dir }}"
  when:
    - platform == "libvirt"
    - destroy is not defined or destroy == false

## using gunzip since unarchive doesn't seem to be able to handle .gz
- name: Unzip RHCOS archive
  ansible.builtin.shell:
    chdir: "{{ artifact_download_dir }}"
    cmd: "gunzip  {{ artifact_download_dir }}/{{ rhcos_bin_archive_name }}"
  when:
    - platform == "libvirt"
    - destroy is not defined or destroy == false

- name: Copy QEMU file to hypervisor host
  ansible.builtin.copy:
    src: "{{ artifact_download_dir }}/{{ rhcos_bin_file_name }}"
    dest: "{{ staging_dir }}"
    mode: '0644'
  when:
    - platform == "libvirt"
    - destroy is not defined or destroy == false
  become: true

- name: Remove temp dir which used for downloading artifacts
  ansible.builtin.file:
    state: absent
    path: "{{ artifact_download_dir }}"

