---
- name: Define temp dir for downloading artifacts
  ansible.builtin.set_fact:
    artifact_download_dir: "{{ staging_dir }}/temp"

- name: Create artifacts folder
  ansible.builtin.file:
    state: directory
    path: "{{ artifact_download_dir }}"



- name: Remove temp dir which used for downloading artifacts
  ansible.builtin.file:
    state: absent
    path: "{{ artifact_download_dir }}"