---
- name: Download Artifacts
  include_role:
    name: openshift-download-artifacts

- name: Create base QEMU image at the desired size
  ansible.builtin.shell: "qemu-img create -f qcow2 -o preallocation=metadata,cluster_size=2M {{ resized_base_qcow }} {{ resized_base_qcow_disk_size }}"

- name: Use base RHCOS image and resize it to the new QEMU image
  ansible.builtin.shell: "virt-resize --quiet --expand /dev/sda4 {{ base_qcow }} {{ resized_base_qcow }}"

- name: Copy QEMU image file to VM storage pool
  ansible.builtin.copy:
    src: "{{ resized_base_qcow }}"
    dest: "{{ cluster_vms_storage_base_dir }}"
    owner: qemu
    group: qemu
    mode: '0775'

- name: Remove file (delete file)
  ansible.builtin.file:
    path: "{{ resized_base_qcow }}"
    state: absent


#- name: Define Hub from xml and set autostart
#  community.libvirt.virt:
#    command: define
#    xml: '{{ lookup("template", "templates/hub.xml.j2") }}'
#    autostart: true